### ISSUE TITLE
In MAD, where's the util?

### ISSUE THREAD

**Issue by chanyyyy** [I-Hope-Peace/ChangeDetectionRepository#1]
As this line in irmad.py,
`from MAD.util import show_variates`
May be my fault, but well I couldn't find neither util nor show_variates.
Hope for reply, thanks.

**Comment by ChenHongruixuan** [comment]
Hi🙂, the function show_variates is used for showing each band of the MAD results. You can just comment out the line. The modified code of MAD has been uploaded.  Since this repository is just made up, there may exist some errors in the code. We will modify them soon.

**Comment by ChenHongruixuan** [comment]
Hi🙂, we have updated the code of MAD and added a test example in the Taizhou Dataset. You can find them in MAD folder.
