### ISSUE TITLE
Inconsistency results with SFA 

### ISSUE THREAD

**Issue by lauraset** [I-Hope-Peace/ChangeDetectionRepository#5]
Hi, @I-Hope-Peace . Thank you for your grear work. When I tested the traditional methods,  the result of SFA is inconsistency with that provided by you. Here, I present the result I generated:
![image](https://user-images.githubusercontent.com/39206462/164979822-b87f93c7-f7c3-4202-9d81-08c054cf1f81.png)

Do you know why it happened? Thank you very much.

**Comment by ChenHongruixuan** [comment]
The visualization of this result is very good and the accuracy should not be low, perhaps you could adjust the hyperparameters.

**Comment by lauraset** [comment]
Thank you very much.
