### ISSUE TITLE
2000TM

### ISSUE THREAD

**Issue by VickyCas** [I-Hope-Peace/ChangeDetectionRepository#6]
Hello, @ChenHongruixuan , thank you for making your work public. 
I don't understand well the file '2000TM' in Dataset\Landsat\TaiZhou, what does it means and how should I get it using my dataset? 
Thank you for your answer.

**Comment by ChenHongruixuan** [comment]
> Hello, @ChenHongruixuan , thank you for making your work public. I don't understand well the file '2000TM' in Dataset\Landsat\TaiZhou, what does it means and how should I get it using my dataset? Thank you for your answer.

Hi, thank you for your inquiry. 2000TM is the pre-change image file. You need to read the image file using GDAL library.
